### ISSUE TITLE
Index page does not render Markdown properly

### ISSUE THREAD

**Issue by greatislander** [sachin10101998/fluidic-11ty#1]
## Describe the bug

The index page (https://github.com/sachin10101998/fluidic-11ty/blob/master/src/index.html) does not render its contents properly using Markdown because it has a `.html` extension instead of `.md`.

### To reproduce

1. Run `npm run eleventy`.
2. Navigate to http://localhost:8080.
3. Inspect the page contents.
4. See that the content from `index.html` is not wrapped in a `<p>` tag.

### Expected behavior

The content of the index page should be rendered into HTML from Markdown.

## Additional context or notes

This issue can be resolved by changing the file extension to `.md`.

**Comment by sachin10101998** [comment]
@greatislander The index page has no content, therefore it doesn't render anything. This is not because the extension is HTML, but because the content which you see is just a comment in markdown and hence it's not rendered. 
I intentionally didn't add anything to the index page so that someone who starts building a site using the starter kit, doesn't have to remove anything from the index page. 11ty processes both HTML and md extension files in a similar way.

**Comment by greatislander** [comment]
Hi @sachin10101998, copying this in from IRC:

When I removed your sample (commented-out) content and replaced it with this:

```
This should be a paragraph with _italics_.
```
I still got unprocessed markdown:

<img width="487" alt="Screen Shot 2020-08-24 at 1 42 58 PM" src="https://user-images.githubusercontent.com/605361/91072685-3fa71080-e610-11ea-93c7-b8dae51a08e4.png">

Changing the file extension to `.md` fixed the issue for me. Please test again and see if you can reproduce this.

<img width="296" alt="Screen Shot 2020-08-24 at 1 44 38 PM" src="https://user-images.githubusercontent.com/605361/91072728-4f265980-e610-11ea-8a19-ff5a1f877467.png">

**Comment by sachin10101998** [comment]
Made the required changes. @greatislander

**Comment by greatislander** [comment]
Fixed in b3efe0a.
